/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_BSMPSMParams_H_
#define	_BSMPSMParams_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeReal.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BSMPSMParams */
typedef struct BSMPSMParams {
	long	*radius	/* OPTIONAL */;
	double	*minimumTimeDelta	/* OPTIONAL */;
	long	*minimumPosDelta	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BSMPSMParams_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BSMPSMParams;

#ifdef __cplusplus
}
#endif

#endif	/* _BSMPSMParams_H_ */
#include <asn_internal.h>
