/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#include "BSMPSMParams.h"

static int
memb_radius_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 1500)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_radius_constr_2 CC_NOTUSED = {
	{ 2, 1 }	/* (1..1500) */,
	-1};
static asn_per_constraints_t asn_PER_memb_radius_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 11,  11,  1,  1500 }	/* (1..1500) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_BSMPSMParams_1[] = {
	{ ATF_POINTER, 3, offsetof(struct BSMPSMParams, radius),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_radius_constr_2, &asn_PER_memb_radius_constr_2,  memb_radius_constraint_1 },
		0, 0, /* No default value */
		"radius"
		},
	{ ATF_POINTER, 2, offsetof(struct BSMPSMParams, minimumTimeDelta),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"minimumTimeDelta"
		},
	{ ATF_POINTER, 1, offsetof(struct BSMPSMParams, minimumPosDelta),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"minimumPosDelta"
		},
};
static const int asn_MAP_BSMPSMParams_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_BSMPSMParams_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_BSMPSMParams_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* radius */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* minimumTimeDelta */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* minimumPosDelta */
};
static asn_SEQUENCE_specifics_t asn_SPC_BSMPSMParams_specs_1 = {
	sizeof(struct BSMPSMParams),
	offsetof(struct BSMPSMParams, _asn_ctx),
	asn_MAP_BSMPSMParams_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_BSMPSMParams_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_BSMPSMParams = {
	"BSMPSMParams",
	"BSMPSMParams",
	&asn_OP_SEQUENCE,
	asn_DEF_BSMPSMParams_tags_1,
	sizeof(asn_DEF_BSMPSMParams_tags_1)
		/sizeof(asn_DEF_BSMPSMParams_tags_1[0]), /* 1 */
	asn_DEF_BSMPSMParams_tags_1,	/* Same as above */
	sizeof(asn_DEF_BSMPSMParams_tags_1)
		/sizeof(asn_DEF_BSMPSMParams_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_BSMPSMParams_1,
	3,	/* Elements count */
	&asn_SPC_BSMPSMParams_specs_1	/* Additional specs */
};

