/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#include "DataRequestMessage.h"

static int
memb_elems_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size <= 10)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_elems_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..10)) */};
static asn_per_constraints_t asn_PER_type_elems_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (SIZE(0..10)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_elems_constr_4 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(0..10)) */};
static asn_per_constraints_t asn_PER_memb_elems_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 4,  4,  0,  10 }	/* (SIZE(0..10)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_elems_4[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_DataRequestElement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_elems_tags_4[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_elems_specs_4 = {
	sizeof(struct DataRequestMessage__elems),
	offsetof(struct DataRequestMessage__elems, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_elems_4 = {
	"elems",
	"elems",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_elems_tags_4,
	sizeof(asn_DEF_elems_tags_4)
		/sizeof(asn_DEF_elems_tags_4[0]) - 1, /* 1 */
	asn_DEF_elems_tags_4,	/* Same as above */
	sizeof(asn_DEF_elems_tags_4)
		/sizeof(asn_DEF_elems_tags_4[0]), /* 2 */
	{ &asn_OER_type_elems_constr_4, &asn_PER_type_elems_constr_4, SEQUENCE_OF_constraint },
	asn_MBR_elems_4,
	1,	/* Single element */
	&asn_SPC_elems_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_DataRequestMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DataRequestMessage, apiDeveloperKey),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IA5String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"apiDeveloperKey"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataRequestMessage, id),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TemporaryID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataRequestMessage, elems),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_elems_4,
		0,
		{ &asn_OER_memb_elems_constr_4, &asn_PER_memb_elems_constr_4,  memb_elems_constraint_1 },
		0, 0, /* No default value */
		"elems"
		},
};
static const ber_tlv_tag_t asn_DEF_DataRequestMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DataRequestMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* apiDeveloperKey */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* elems */
};
asn_SEQUENCE_specifics_t asn_SPC_DataRequestMessage_specs_1 = {
	sizeof(struct DataRequestMessage),
	offsetof(struct DataRequestMessage, _asn_ctx),
	asn_MAP_DataRequestMessage_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DataRequestMessage = {
	"DataRequestMessage",
	"DataRequestMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_DataRequestMessage_tags_1,
	sizeof(asn_DEF_DataRequestMessage_tags_1)
		/sizeof(asn_DEF_DataRequestMessage_tags_1[0]), /* 1 */
	asn_DEF_DataRequestMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_DataRequestMessage_tags_1)
		/sizeof(asn_DEF_DataRequestMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DataRequestMessage_1,
	3,	/* Elements count */
	&asn_SPC_DataRequestMessage_specs_1	/* Additional specs */
};

