/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_DataRequestElement_H_
#define	_DataRequestElement_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DSRCmsgID.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "BSMPSMParams.h"
#include "MAPSPaTParams.h"
#include "SignalAheadParams.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DataRequestElement__parameters_PR {
	DataRequestElement__parameters_PR_NOTHING,	/* No components present */
	DataRequestElement__parameters_PR_BSMPSMParams,
	DataRequestElement__parameters_PR_MAPSPaTParams,
	DataRequestElement__parameters_PR_SignalAheadParams
} DataRequestElement__parameters_PR;

/* DataRequestElement */
typedef struct DataRequestElement {
	DSRCmsgID_t	 messageType;
	struct DataRequestElement__parameters {
		DataRequestElement__parameters_PR present;
		union DataRequestElement__parameters_u {
			BSMPSMParams_t	 BSMPSMParams;
			MAPSPaTParams_t	 MAPSPaTParams;
			SignalAheadParams_t	 SignalAheadParams;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} parameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataRequestElement_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataRequestElement;
extern asn_SEQUENCE_specifics_t asn_SPC_DataRequestElement_specs_1;
extern asn_TYPE_member_t asn_MBR_DataRequestElement_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _DataRequestElement_H_ */
#include <asn_internal.h>
