/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_DataRequestMessage_H_
#define	_DataRequestMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include "TemporaryID.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DataRequestElement;

/* DataRequestMessage */
typedef struct DataRequestMessage {
	IA5String_t	 apiDeveloperKey;
	TemporaryID_t	 id;
	struct DataRequestMessage__elems {
		A_SEQUENCE_OF(struct DataRequestElement) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} elems;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataRequestMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DataRequestMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_DataRequestMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_DataRequestMessage_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DataRequestElement.h"

#endif	/* _DataRequestMessage_H_ */
#include <asn_internal.h>
