/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_DisconnectMessage_H_
#define	_DisconnectMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DisconnectMessage */
typedef struct DisconnectMessage {
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DisconnectMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DisconnectMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_DisconnectMessage_specs_1;

#ifdef __cplusplus
}
#endif

#endif	/* _DisconnectMessage_H_ */
#include <asn_internal.h>
