/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_LocationFilter_H_
#define	_LocationFilter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LocationFilter {
	LocationFilter_radius	= 0,
	LocationFilter_ahead	= 1,
	LocationFilter_none	= 2
} e_LocationFilter;

/* LocationFilter */
typedef long	 LocationFilter_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_LocationFilter_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_LocationFilter;
extern const asn_INTEGER_specifics_t asn_SPC_LocationFilter_specs_1;
asn_struct_free_f LocationFilter_free;
asn_struct_print_f LocationFilter_print;
asn_constr_check_f LocationFilter_constraint;
ber_type_decoder_f LocationFilter_decode_ber;
der_type_encoder_f LocationFilter_encode_der;
xer_type_decoder_f LocationFilter_decode_xer;
xer_type_encoder_f LocationFilter_encode_xer;
oer_type_decoder_f LocationFilter_decode_oer;
oer_type_encoder_f LocationFilter_encode_oer;
per_type_decoder_f LocationFilter_decode_uper;
per_type_encoder_f LocationFilter_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _LocationFilter_H_ */
#include <asn_internal.h>
