/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_MAPSPaTParams_H_
#define	_MAPSPaTParams_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LocationFilter.h"
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MAPSPaTParams */
typedef struct MAPSPaTParams {
	LocationFilter_t	*locationFilter	/* OPTIONAL */;
	long	*radius	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MAPSPaTParams_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MAPSPaTParams;

#ifdef __cplusplus
}
#endif

#endif	/* _MAPSPaTParams_H_ */
#include <asn_internal.h>
