/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#include "MovementAndManeuver.h"

asn_TYPE_member_t asn_MBR_MovementAndManeuver_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MovementAndManeuver, signalGroup),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SignalGroupID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signalGroup"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MovementAndManeuver, maneuvers),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Maneuvers,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"maneuvers"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MovementAndManeuver, state_time_speed),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MovementEventList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"state-time-speed"
		},
};
static const ber_tlv_tag_t asn_DEF_MovementAndManeuver_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MovementAndManeuver_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* signalGroup */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* maneuvers */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* state-time-speed */
};
asn_SEQUENCE_specifics_t asn_SPC_MovementAndManeuver_specs_1 = {
	sizeof(struct MovementAndManeuver),
	offsetof(struct MovementAndManeuver, _asn_ctx),
	asn_MAP_MovementAndManeuver_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MovementAndManeuver = {
	"MovementAndManeuver",
	"MovementAndManeuver",
	&asn_OP_SEQUENCE,
	asn_DEF_MovementAndManeuver_tags_1,
	sizeof(asn_DEF_MovementAndManeuver_tags_1)
		/sizeof(asn_DEF_MovementAndManeuver_tags_1[0]), /* 1 */
	asn_DEF_MovementAndManeuver_tags_1,	/* Same as above */
	sizeof(asn_DEF_MovementAndManeuver_tags_1)
		/sizeof(asn_DEF_MovementAndManeuver_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MovementAndManeuver_1,
	3,	/* Elements count */
	&asn_SPC_MovementAndManeuver_specs_1	/* Additional specs */
};

