/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_MovementAndManeuver_H_
#define	_MovementAndManeuver_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SignalGroupID.h"
#include "Maneuvers.h"
#include "MovementEventList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* MovementAndManeuver */
typedef struct MovementAndManeuver {
	SignalGroupID_t	 signalGroup;
	Maneuvers_t	 maneuvers;
	MovementEventList_t	 state_time_speed;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MovementAndManeuver_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MovementAndManeuver;
extern asn_SEQUENCE_specifics_t asn_SPC_MovementAndManeuver_specs_1;
extern asn_TYPE_member_t asn_MBR_MovementAndManeuver_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _MovementAndManeuver_H_ */
#include <asn_internal.h>
