/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_Scope_H_
#define	_Scope_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Scope {
	Scope_intersection	= 0,
	Scope_currentDirection	= 1
} e_Scope;

/* Scope */
typedef long	 Scope_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Scope_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Scope;
extern const asn_INTEGER_specifics_t asn_SPC_Scope_specs_1;
asn_struct_free_f Scope_free;
asn_struct_print_f Scope_print;
asn_constr_check_f Scope_constraint;
ber_type_decoder_f Scope_decode_ber;
der_type_encoder_f Scope_encode_der;
xer_type_decoder_f Scope_decode_xer;
xer_type_encoder_f Scope_encode_xer;
oer_type_decoder_f Scope_decode_oer;
oer_type_encoder_f Scope_encode_oer;
per_type_decoder_f Scope_decode_uper;
per_type_encoder_f Scope_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Scope_H_ */
#include <asn_internal.h>
