/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_SignalAheadParams_H_
#define	_SignalAheadParams_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Scope.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignalAheadParams */
typedef struct SignalAheadParams {
	Scope_t	*scope	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalAheadParams_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalAheadParams;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalAheadParams_H_ */
#include <asn_internal.h>
