/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_SignalAheadMessage_H_
#define	_SignalAheadMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MinuteOfTheYear.h"
#include "DescriptiveName.h"
#include "IntersectionReferenceID.h"
#include "Position3D.h"
#include "MovementAndManeuverList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SignalAheadMessage */
typedef struct SignalAheadMessage {
	MinuteOfTheYear_t	*timeStamp	/* OPTIONAL */;
	DescriptiveName_t	*intersectionName	/* OPTIONAL */;
	IntersectionReferenceID_t	 intersectionId;
	Position3D_t	 refPoint;
	MovementAndManeuverList_t	 movements;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SignalAheadMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalAheadMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_SignalAheadMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_SignalAheadMessage_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _SignalAheadMessage_H_ */
#include <asn_internal.h>
