/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#include "SignalAheadMessage.h"

asn_TYPE_member_t asn_MBR_SignalAheadMessage_1[] = {
	{ ATF_POINTER, 2, offsetof(struct SignalAheadMessage, timeStamp),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MinuteOfTheYear,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"timeStamp"
		},
	{ ATF_POINTER, 1, offsetof(struct SignalAheadMessage, intersectionName),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DescriptiveName,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"intersectionName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignalAheadMessage, intersectionId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IntersectionReferenceID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"intersectionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignalAheadMessage, refPoint),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Position3D,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"refPoint"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SignalAheadMessage, movements),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MovementAndManeuverList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"movements"
		},
};
static const int asn_MAP_SignalAheadMessage_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_SignalAheadMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SignalAheadMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* timeStamp */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* intersectionName */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* intersectionId */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* refPoint */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* movements */
};
asn_SEQUENCE_specifics_t asn_SPC_SignalAheadMessage_specs_1 = {
	sizeof(struct SignalAheadMessage),
	offsetof(struct SignalAheadMessage, _asn_ctx),
	asn_MAP_SignalAheadMessage_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SignalAheadMessage_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SignalAheadMessage = {
	"SignalAheadMessage",
	"SignalAheadMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_SignalAheadMessage_tags_1,
	sizeof(asn_DEF_SignalAheadMessage_tags_1)
		/sizeof(asn_DEF_SignalAheadMessage_tags_1[0]), /* 1 */
	asn_DEF_SignalAheadMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_SignalAheadMessage_tags_1)
		/sizeof(asn_DEF_SignalAheadMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SignalAheadMessage_1,
	5,	/* Elements count */
	&asn_SPC_SignalAheadMessage_specs_1	/* Additional specs */
};

