/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "j2735.asn"
 * 	`asn1c -fcompound-names -pdu=auto`
 */

#ifndef	_StatusMessage_H_
#define	_StatusMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <IA5String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* StatusMessage */
typedef struct StatusMessage {
	IA5String_t	 severity;
	IA5String_t	 message;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} StatusMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_StatusMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_StatusMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_StatusMessage_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _StatusMessage_H_ */
#include <asn_internal.h>
