apiVersion: v1
kind: Service
metadata:
  name: mosquitto-broker-service
spec:
  type: NodePort
  ports:
    - name: websocket
      port: 8080
      targetPort: 8080
      nodePort: 30889
  selector:
    app: mosquitto-broker