apiVersion: v1
kind: Service
metadata:
  name: sdmap-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30891
  selector:
    run: sdmap-client
