apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdmap-agent-psm
spec:
  selector:
    matchLabels:
      run: sdmap-agent-psm
  replicas: 1
  template:
    metadata:
      labels:
        run: sdmap-agent-psm
    spec:
      containers:
      - name: sdmap-agent-psm
        image: yhseanhsu/sdmap-agent:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            ephemeral-storage: "4Gi"
        env:
        - name: PUBFREQ
          value: "1"
        - name: PUBSERVER
          value: mosquitto-internal-service.default.svc.cluster.local:1883
        - name: SUBSERVER
          value: mosquitto-internal-service.default.svc.cluster.local:1883
        - name: PUBTOPIC
          value: DecodedPSM
        - name: SUBTOPIC
          value: VSCMobility/1.0.0/PSM/Video/Some_Merlin
        - name: FORMAT
          value: "3"
        args:
        - "-log=debug"
