apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdmap-client
spec:
  selector:
    matchLabels:
      run: sdmap-client
  replicas: 1
  template:
    metadata:
      labels:
        run: sdmap-client
    spec:
      containers:
      - name: sdmap-client
        image: yhseanhsu/sdmap-client:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            ephemeral-storage: "4Gi"
