apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdmap-agent-spat
spec:
  selector:
    matchLabels:
      run: sdmap-agent-spat
  replicas: 1
  template:
    metadata:
      labels:
        run: sdmap-agent-spat
    spec:
      containers:
      - name: sdmap-agent-spat
        image: yhseanhsu/sdmap-agent:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            ephemeral-storage: "2Gi"
          limits:
            memory: "2Gi"
            ephemeral-storage: "4Gi"
        env:
        - name: PUBFREQ
          value: "200"
        - name: PUBSERVER
          value: decoded-int-broker.default.svc.cluster.local:1883
        - name: SUBSERVER
          value: mosquitto-internal-service.default.svc.cluster.local:1883
        - name: PUBTOPIC
          value: DecodedSPaT
        - name: SUBTOPIC
          value: VSCMobility/1.0.0/SPaT/#
        - name: FORMAT
          value: "2"
        args:
        - "-log=debug"
